import { FIRST, MIDDLE, LAST } from './actionNames';

const initialStore = {
  item__1: 1,
  item__2: 2,
  item__3: 3,
  item__4: 4,
  item__5: 5,
  item__6: 6,
  item__7: 7,
  item__8: 8,
  item__9: 9,
  item__10: 10,
  item__11: 11,
  item__12: 12,
  item__13: 13,
  item__14: 14,
  item__15: 15,
  item__16: 16,
  item__17: 17,
  item__18: 18,
  item__19: 19,
  item__20: 20,
  item__21: 21,
  item__22: 22,
  item__23: 23,
  item__24: 24,
  item__25: 25,
  item__26: 26,
  item__27: 27,
  item__28: 28,
  item__29: 29,
  item__30: 30,
  item__31: 31,
  item__32: 32,
  item__33: 33,
  item__34: 34,
  item__35: 35,
  item__36: 36,
  item__37: 37,
  item__38: 38,
  item__39: 39,
  item__40: 40,
  item__41: 41,
  item__42: 42,
  item__43: 43,
  item__44: 44,
  item__45: 45,
  item__46: 46,
  item__47: 47,
  item__48: 48,
  item__49: 49,
  item__50: 50,
  item__51: 51,
  item__52: 52,
  item__53: 53,
  item__54: 54,
  item__55: 55,
  item__56: 56,
  item__57: 57,
  item__58: 58,
  item__59: 59,
  item__60: 60,
  item__61: 61,
  item__62: 62,
  item__63: 63,
  item__64: 64,
  item__65: 65,
  item__66: 66,
  item__67: 67,
  item__68: 68,
  item__69: 69,
  item__70: 70,
  item__71: 71,
  item__72: 72,
  item__73: 73,
  item__74: 74,
  item__75: 75,
  item__76: 76,
  item__77: 77,
  item__78: 78,
  item__79: 79,
  item__80: 80,
  item__81: 81,
  item__82: 82,
  item__83: 83,
  item__84: 84,
  item__85: 85,
  item__86: 86,
  item__87: 87,
  item__88: 88,
  item__89: 89,
  item__90: 90,
  item__91: 91,
  item__92: 92,
  item__93: 93,
  item__94: 94,
  item__95: 95,
  item__96: 96,
  item__97: 97,
  item__98: 98,
  item__99: 99,
  item__100: 100
};

const functions = {
  [FIRST]: (store) => ({ ...store }),
  'OBJECT__TEST_TYPE--2': (store) => store,
  'OBJECT__TEST_TYPE--3': (store) => store,
  'OBJECT__TEST_TYPE--4': (store) => store,
  'OBJECT__TEST_TYPE--5': (store) => store,
  'OBJECT__TEST_TYPE--6': (store) => store,
  'OBJECT__TEST_TYPE--7': (store) => store,
  'OBJECT__TEST_TYPE--8': (store) => store,
  'OBJECT__TEST_TYPE--9': (store) => store,
  'OBJECT__TEST_TYPE--10': (store) => store,
  'OBJECT__TEST_TYPE--11': (store) => store,
  'OBJECT__TEST_TYPE--12': (store) => store,
  'OBJECT__TEST_TYPE--13': (store) => store,
  'OBJECT__TEST_TYPE--14': (store) => store,
  'OBJECT__TEST_TYPE--15': (store) => store,
  'OBJECT__TEST_TYPE--16': (store) => store,
  'OBJECT__TEST_TYPE--17': (store) => store,
  'OBJECT__TEST_TYPE--18': (store) => store,
  'OBJECT__TEST_TYPE--19': (store) => store,
  'OBJECT__TEST_TYPE--20': (store) => store,
  'OBJECT__TEST_TYPE--21': (store) => store,
  'OBJECT__TEST_TYPE--22': (store) => store,
  'OBJECT__TEST_TYPE--23': (store) => store,
  'OBJECT__TEST_TYPE--24': (store) => store,
  'OBJECT__TEST_TYPE--25': (store) => store,
  'OBJECT__TEST_TYPE--26': (store) => store,
  'OBJECT__TEST_TYPE--27': (store) => store,
  'OBJECT__TEST_TYPE--28': (store) => store,
  'OBJECT__TEST_TYPE--29': (store) => store,
  'OBJECT__TEST_TYPE--30': (store) => store,
  'OBJECT__TEST_TYPE--31': (store) => store,
  'OBJECT__TEST_TYPE--32': (store) => store,
  'OBJECT__TEST_TYPE--33': (store) => store,
  'OBJECT__TEST_TYPE--34': (store) => store,
  'OBJECT__TEST_TYPE--35': (store) => store,
  'OBJECT__TEST_TYPE--36': (store) => store,
  'OBJECT__TEST_TYPE--37': (store) => store,
  'OBJECT__TEST_TYPE--38': (store) => store,
  'OBJECT__TEST_TYPE--39': (store) => store,
  'OBJECT__TEST_TYPE--40': (store) => store,
  'OBJECT__TEST_TYPE--41': (store) => store,
  'OBJECT__TEST_TYPE--42': (store) => store,
  'OBJECT__TEST_TYPE--43': (store) => store,
  'OBJECT__TEST_TYPE--44': (store) => store,
  'OBJECT__TEST_TYPE--45': (store) => store,
  'OBJECT__TEST_TYPE--46': (store) => store,
  'OBJECT__TEST_TYPE--47': (store) => store,
  'OBJECT__TEST_TYPE--48': (store) => store,
  'OBJECT__TEST_TYPE--49': (store) => store,
  'OBJECT__TEST_TYPE--50': (store) => store,
  'OBJECT__TEST_TYPE--51': (store) => store,
  'OBJECT__TEST_TYPE--52': (store) => store,
  'OBJECT__TEST_TYPE--53': (store) => store,
  'OBJECT__TEST_TYPE--54': (store) => store,
  'OBJECT__TEST_TYPE--55': (store) => store,
  'OBJECT__TEST_TYPE--56': (store) => store,
  'OBJECT__TEST_TYPE--57': (store) => store,
  'OBJECT__TEST_TYPE--58': (store) => store,
  'OBJECT__TEST_TYPE--59': (store) => store,
  'OBJECT__TEST_TYPE--60': (store) => store,
  'OBJECT__TEST_TYPE--61': (store) => store,
  'OBJECT__TEST_TYPE--62': (store) => store,
  'OBJECT__TEST_TYPE--63': (store) => store,
  'OBJECT__TEST_TYPE--64': (store) => store,
  'OBJECT__TEST_TYPE--65': (store) => store,
  'OBJECT__TEST_TYPE--66': (store) => store,
  'OBJECT__TEST_TYPE--67': (store) => store,
  'OBJECT__TEST_TYPE--68': (store) => store,
  'OBJECT__TEST_TYPE--69': (store) => store,
  'OBJECT__TEST_TYPE--70': (store) => store,
  'OBJECT__TEST_TYPE--71': (store) => store,
  'OBJECT__TEST_TYPE--72': (store) => store,
  'OBJECT__TEST_TYPE--73': (store) => store,
  'OBJECT__TEST_TYPE--74': (store) => store,
  'OBJECT__TEST_TYPE--75': (store) => store,
  'OBJECT__TEST_TYPE--76': (store) => store,
  'OBJECT__TEST_TYPE--77': (store) => store,
  'OBJECT__TEST_TYPE--78': (store) => store,
  'OBJECT__TEST_TYPE--79': (store) => store,
  'OBJECT__TEST_TYPE--80': (store) => store,
  'OBJECT__TEST_TYPE--81': (store) => store,
  'OBJECT__TEST_TYPE--82': (store) => store,
  'OBJECT__TEST_TYPE--83': (store) => store,
  'OBJECT__TEST_TYPE--84': (store) => store,
  'OBJECT__TEST_TYPE--85': (store) => store,
  'OBJECT__TEST_TYPE--86': (store) => store,
  'OBJECT__TEST_TYPE--87': (store) => store,
  'OBJECT__TEST_TYPE--88': (store) => store,
  'OBJECT__TEST_TYPE--89': (store) => store,
  'OBJECT__TEST_TYPE--90': (store) => store,
  'OBJECT__TEST_TYPE--91': (store) => store,
  'OBJECT__TEST_TYPE--92': (store) => store,
  'OBJECT__TEST_TYPE--93': (store) => store,
  'OBJECT__TEST_TYPE--94': (store) => store,
  'OBJECT__TEST_TYPE--95': (store) => store,
  'OBJECT__TEST_TYPE--96': (store) => store,
  'OBJECT__TEST_TYPE--97': (store) => store,
  'OBJECT__TEST_TYPE--98': (store) => store,
  'OBJECT__TEST_TYPE--99': (store) => store,
  'OBJECT__TEST_TYPE--100': (store) => store,
  'OBJECT__TEST_TYPE--101': (store) => store,
  'OBJECT__TEST_TYPE--102': (store) => store,
  'OBJECT__TEST_TYPE--103': (store) => store,
  'OBJECT__TEST_TYPE--104': (store) => store,
  'OBJECT__TEST_TYPE--105': (store) => store,
  'OBJECT__TEST_TYPE--106': (store) => store,
  'OBJECT__TEST_TYPE--107': (store) => store,
  'OBJECT__TEST_TYPE--108': (store) => store,
  'OBJECT__TEST_TYPE--109': (store) => store,
  'OBJECT__TEST_TYPE--110': (store) => store,
  'OBJECT__TEST_TYPE--111': (store) => store,
  'OBJECT__TEST_TYPE--112': (store) => store,
  'OBJECT__TEST_TYPE--113': (store) => store,
  'OBJECT__TEST_TYPE--114': (store) => store,
  'OBJECT__TEST_TYPE--115': (store) => store,
  'OBJECT__TEST_TYPE--116': (store) => store,
  'OBJECT__TEST_TYPE--117': (store) => store,
  'OBJECT__TEST_TYPE--118': (store) => store,
  'OBJECT__TEST_TYPE--119': (store) => store,
  'OBJECT__TEST_TYPE--120': (store) => store,
  'OBJECT__TEST_TYPE--121': (store) => store,
  'OBJECT__TEST_TYPE--122': (store) => store,
  'OBJECT__TEST_TYPE--123': (store) => store,
  'OBJECT__TEST_TYPE--124': (store) => store,
  'OBJECT__TEST_TYPE--125': (store) => store,
  'OBJECT__TEST_TYPE--126': (store) => store,
  'OBJECT__TEST_TYPE--127': (store) => store,
  'OBJECT__TEST_TYPE--128': (store) => store,
  'OBJECT__TEST_TYPE--129': (store) => store,
  'OBJECT__TEST_TYPE--130': (store) => store,
  'OBJECT__TEST_TYPE--131': (store) => store,
  'OBJECT__TEST_TYPE--132': (store) => store,
  'OBJECT__TEST_TYPE--133': (store) => store,
  'OBJECT__TEST_TYPE--134': (store) => store,
  'OBJECT__TEST_TYPE--135': (store) => store,
  'OBJECT__TEST_TYPE--136': (store) => store,
  'OBJECT__TEST_TYPE--137': (store) => store,
  'OBJECT__TEST_TYPE--138': (store) => store,
  'OBJECT__TEST_TYPE--139': (store) => store,
  'OBJECT__TEST_TYPE--140': (store) => store,
  'OBJECT__TEST_TYPE--141': (store) => store,
  'OBJECT__TEST_TYPE--142': (store) => store,
  'OBJECT__TEST_TYPE--143': (store) => store,
  'OBJECT__TEST_TYPE--144': (store) => store,
  'OBJECT__TEST_TYPE--145': (store) => store,
  'OBJECT__TEST_TYPE--146': (store) => store,
  'OBJECT__TEST_TYPE--147': (store) => store,
  'OBJECT__TEST_TYPE--148': (store) => store,
  'OBJECT__TEST_TYPE--149': (store) => store,
  'OBJECT__TEST_TYPE--150': (store) => store,
  'OBJECT__TEST_TYPE--151': (store) => store,
  'OBJECT__TEST_TYPE--152': (store) => store,
  'OBJECT__TEST_TYPE--153': (store) => store,
  'OBJECT__TEST_TYPE--154': (store) => store,
  'OBJECT__TEST_TYPE--155': (store) => store,
  'OBJECT__TEST_TYPE--156': (store) => store,
  'OBJECT__TEST_TYPE--157': (store) => store,
  'OBJECT__TEST_TYPE--158': (store) => store,
  'OBJECT__TEST_TYPE--159': (store) => store,
  'OBJECT__TEST_TYPE--160': (store) => store,
  'OBJECT__TEST_TYPE--161': (store) => store,
  'OBJECT__TEST_TYPE--162': (store) => store,
  'OBJECT__TEST_TYPE--163': (store) => store,
  'OBJECT__TEST_TYPE--164': (store) => store,
  'OBJECT__TEST_TYPE--165': (store) => store,
  'OBJECT__TEST_TYPE--166': (store) => store,
  'OBJECT__TEST_TYPE--167': (store) => store,
  'OBJECT__TEST_TYPE--168': (store) => store,
  'OBJECT__TEST_TYPE--169': (store) => store,
  'OBJECT__TEST_TYPE--170': (store) => store,
  'OBJECT__TEST_TYPE--171': (store) => store,
  'OBJECT__TEST_TYPE--172': (store) => store,
  'OBJECT__TEST_TYPE--173': (store) => store,
  'OBJECT__TEST_TYPE--174': (store) => store,
  'OBJECT__TEST_TYPE--175': (store) => store,
  'OBJECT__TEST_TYPE--176': (store) => store,
  'OBJECT__TEST_TYPE--177': (store) => store,
  'OBJECT__TEST_TYPE--178': (store) => store,
  'OBJECT__TEST_TYPE--179': (store) => store,
  'OBJECT__TEST_TYPE--180': (store) => store,
  'OBJECT__TEST_TYPE--181': (store) => store,
  'OBJECT__TEST_TYPE--182': (store) => store,
  'OBJECT__TEST_TYPE--183': (store) => store,
  'OBJECT__TEST_TYPE--184': (store) => store,
  'OBJECT__TEST_TYPE--185': (store) => store,
  'OBJECT__TEST_TYPE--186': (store) => store,
  'OBJECT__TEST_TYPE--187': (store) => store,
  'OBJECT__TEST_TYPE--188': (store) => store,
  'OBJECT__TEST_TYPE--189': (store) => store,
  'OBJECT__TEST_TYPE--190': (store) => store,
  'OBJECT__TEST_TYPE--191': (store) => store,
  'OBJECT__TEST_TYPE--192': (store) => store,
  'OBJECT__TEST_TYPE--193': (store) => store,
  'OBJECT__TEST_TYPE--194': (store) => store,
  'OBJECT__TEST_TYPE--195': (store) => store,
  'OBJECT__TEST_TYPE--196': (store) => store,
  'OBJECT__TEST_TYPE--197': (store) => store,
  'OBJECT__TEST_TYPE--198': (store) => store,
  'OBJECT__TEST_TYPE--199': (store) => store,
  'OBJECT__TEST_TYPE--200': (store) => store,
  'OBJECT__TEST_TYPE--201': (store) => store,
  'OBJECT__TEST_TYPE--202': (store) => store,
  'OBJECT__TEST_TYPE--203': (store) => store,
  'OBJECT__TEST_TYPE--204': (store) => store,
  'OBJECT__TEST_TYPE--205': (store) => store,
  'OBJECT__TEST_TYPE--206': (store) => store,
  'OBJECT__TEST_TYPE--207': (store) => store,
  'OBJECT__TEST_TYPE--208': (store) => store,
  'OBJECT__TEST_TYPE--209': (store) => store,
  'OBJECT__TEST_TYPE--210': (store) => store,
  'OBJECT__TEST_TYPE--211': (store) => store,
  'OBJECT__TEST_TYPE--212': (store) => store,
  'OBJECT__TEST_TYPE--213': (store) => store,
  'OBJECT__TEST_TYPE--214': (store) => store,
  'OBJECT__TEST_TYPE--215': (store) => store,
  'OBJECT__TEST_TYPE--216': (store) => store,
  'OBJECT__TEST_TYPE--217': (store) => store,
  'OBJECT__TEST_TYPE--218': (store) => store,
  'OBJECT__TEST_TYPE--219': (store) => store,
  'OBJECT__TEST_TYPE--220': (store) => store,
  'OBJECT__TEST_TYPE--221': (store) => store,
  'OBJECT__TEST_TYPE--222': (store) => store,
  'OBJECT__TEST_TYPE--223': (store) => store,
  'OBJECT__TEST_TYPE--224': (store) => store,
  'OBJECT__TEST_TYPE--225': (store) => store,
  'OBJECT__TEST_TYPE--226': (store) => store,
  'OBJECT__TEST_TYPE--227': (store) => store,
  'OBJECT__TEST_TYPE--228': (store) => store,
  'OBJECT__TEST_TYPE--229': (store) => store,
  'OBJECT__TEST_TYPE--230': (store) => store,
  'OBJECT__TEST_TYPE--231': (store) => store,
  'OBJECT__TEST_TYPE--232': (store) => store,
  'OBJECT__TEST_TYPE--233': (store) => store,
  'OBJECT__TEST_TYPE--234': (store) => store,
  'OBJECT__TEST_TYPE--235': (store) => store,
  'OBJECT__TEST_TYPE--236': (store) => store,
  'OBJECT__TEST_TYPE--237': (store) => store,
  'OBJECT__TEST_TYPE--238': (store) => store,
  'OBJECT__TEST_TYPE--239': (store) => store,
  'OBJECT__TEST_TYPE--240': (store) => store,
  'OBJECT__TEST_TYPE--241': (store) => store,
  'OBJECT__TEST_TYPE--242': (store) => store,
  'OBJECT__TEST_TYPE--243': (store) => store,
  'OBJECT__TEST_TYPE--244': (store) => store,
  'OBJECT__TEST_TYPE--245': (store) => store,
  'OBJECT__TEST_TYPE--246': (store) => store,
  'OBJECT__TEST_TYPE--247': (store) => store,
  'OBJECT__TEST_TYPE--248': (store) => store,
  'OBJECT__TEST_TYPE--249': (store) => store,
  'OBJECT__TEST_TYPE--250': (store) => store,
  'OBJECT__TEST_TYPE--251': (store) => store,
  'OBJECT__TEST_TYPE--252': (store) => store,
  'OBJECT__TEST_TYPE--253': (store) => store,
  'OBJECT__TEST_TYPE--254': (store) => store,
  'OBJECT__TEST_TYPE--255': (store) => store,
  'OBJECT__TEST_TYPE--256': (store) => store,
  'OBJECT__TEST_TYPE--257': (store) => store,
  'OBJECT__TEST_TYPE--258': (store) => store,
  'OBJECT__TEST_TYPE--259': (store) => store,
  'OBJECT__TEST_TYPE--260': (store) => store,
  'OBJECT__TEST_TYPE--261': (store) => store,
  'OBJECT__TEST_TYPE--262': (store) => store,
  'OBJECT__TEST_TYPE--263': (store) => store,
  'OBJECT__TEST_TYPE--264': (store) => store,
  'OBJECT__TEST_TYPE--265': (store) => store,
  'OBJECT__TEST_TYPE--266': (store) => store,
  'OBJECT__TEST_TYPE--267': (store) => store,
  'OBJECT__TEST_TYPE--268': (store) => store,
  'OBJECT__TEST_TYPE--269': (store) => store,
  'OBJECT__TEST_TYPE--270': (store) => store,
  'OBJECT__TEST_TYPE--271': (store) => store,
  'OBJECT__TEST_TYPE--272': (store) => store,
  'OBJECT__TEST_TYPE--273': (store) => store,
  'OBJECT__TEST_TYPE--274': (store) => store,
  'OBJECT__TEST_TYPE--275': (store) => store,
  'OBJECT__TEST_TYPE--276': (store) => store,
  'OBJECT__TEST_TYPE--277': (store) => store,
  'OBJECT__TEST_TYPE--278': (store) => store,
  'OBJECT__TEST_TYPE--279': (store) => store,
  'OBJECT__TEST_TYPE--280': (store) => store,
  'OBJECT__TEST_TYPE--281': (store) => store,
  'OBJECT__TEST_TYPE--282': (store) => store,
  'OBJECT__TEST_TYPE--283': (store) => store,
  'OBJECT__TEST_TYPE--284': (store) => store,
  'OBJECT__TEST_TYPE--285': (store) => store,
  'OBJECT__TEST_TYPE--286': (store) => store,
  'OBJECT__TEST_TYPE--287': (store) => store,
  'OBJECT__TEST_TYPE--288': (store) => store,
  'OBJECT__TEST_TYPE--289': (store) => store,
  'OBJECT__TEST_TYPE--290': (store) => store,
  'OBJECT__TEST_TYPE--291': (store) => store,
  'OBJECT__TEST_TYPE--292': (store) => store,
  'OBJECT__TEST_TYPE--293': (store) => store,
  'OBJECT__TEST_TYPE--294': (store) => store,
  'OBJECT__TEST_TYPE--295': (store) => store,
  'OBJECT__TEST_TYPE--296': (store) => store,
  'OBJECT__TEST_TYPE--297': (store) => store,
  'OBJECT__TEST_TYPE--298': (store) => store,
  'OBJECT__TEST_TYPE--299': (store) => store,
  'OBJECT__TEST_TYPE--300': (store) => store,
  'OBJECT__TEST_TYPE--301': (store) => store,
  'OBJECT__TEST_TYPE--302': (store) => store,
  'OBJECT__TEST_TYPE--303': (store) => store,
  'OBJECT__TEST_TYPE--304': (store) => store,
  'OBJECT__TEST_TYPE--305': (store) => store,
  'OBJECT__TEST_TYPE--306': (store) => store,
  'OBJECT__TEST_TYPE--307': (store) => store,
  'OBJECT__TEST_TYPE--308': (store) => store,
  'OBJECT__TEST_TYPE--309': (store) => store,
  'OBJECT__TEST_TYPE--310': (store) => store,
  'OBJECT__TEST_TYPE--311': (store) => store,
  'OBJECT__TEST_TYPE--312': (store) => store,
  'OBJECT__TEST_TYPE--313': (store) => store,
  'OBJECT__TEST_TYPE--314': (store) => store,
  'OBJECT__TEST_TYPE--315': (store) => store,
  'OBJECT__TEST_TYPE--316': (store) => store,
  'OBJECT__TEST_TYPE--317': (store) => store,
  'OBJECT__TEST_TYPE--318': (store) => store,
  'OBJECT__TEST_TYPE--319': (store) => store,
  'OBJECT__TEST_TYPE--320': (store) => store,
  'OBJECT__TEST_TYPE--321': (store) => store,
  'OBJECT__TEST_TYPE--322': (store) => store,
  'OBJECT__TEST_TYPE--323': (store) => store,
  'OBJECT__TEST_TYPE--324': (store) => store,
  'OBJECT__TEST_TYPE--325': (store) => store,
  'OBJECT__TEST_TYPE--326': (store) => store,
  'OBJECT__TEST_TYPE--327': (store) => store,
  'OBJECT__TEST_TYPE--328': (store) => store,
  'OBJECT__TEST_TYPE--329': (store) => store,
  'OBJECT__TEST_TYPE--330': (store) => store,
  'OBJECT__TEST_TYPE--331': (store) => store,
  'OBJECT__TEST_TYPE--332': (store) => store,
  'OBJECT__TEST_TYPE--333': (store) => store,
  'OBJECT__TEST_TYPE--334': (store) => store,
  'OBJECT__TEST_TYPE--335': (store) => store,
  'OBJECT__TEST_TYPE--336': (store) => store,
  'OBJECT__TEST_TYPE--337': (store) => store,
  'OBJECT__TEST_TYPE--338': (store) => store,
  'OBJECT__TEST_TYPE--339': (store) => store,
  'OBJECT__TEST_TYPE--340': (store) => store,
  'OBJECT__TEST_TYPE--341': (store) => store,
  'OBJECT__TEST_TYPE--342': (store) => store,
  'OBJECT__TEST_TYPE--343': (store) => store,
  'OBJECT__TEST_TYPE--344': (store) => store,
  'OBJECT__TEST_TYPE--345': (store) => store,
  'OBJECT__TEST_TYPE--346': (store) => store,
  'OBJECT__TEST_TYPE--347': (store) => store,
  'OBJECT__TEST_TYPE--348': (store) => store,
  'OBJECT__TEST_TYPE--349': (store) => store,
  'OBJECT__TEST_TYPE--350': (store) => store,
  'OBJECT__TEST_TYPE--351': (store) => store,
  'OBJECT__TEST_TYPE--352': (store) => store,
  'OBJECT__TEST_TYPE--353': (store) => store,
  'OBJECT__TEST_TYPE--354': (store) => store,
  'OBJECT__TEST_TYPE--355': (store) => store,
  'OBJECT__TEST_TYPE--356': (store) => store,
  'OBJECT__TEST_TYPE--357': (store) => store,
  'OBJECT__TEST_TYPE--358': (store) => store,
  'OBJECT__TEST_TYPE--359': (store) => store,
  'OBJECT__TEST_TYPE--360': (store) => store,
  'OBJECT__TEST_TYPE--361': (store) => store,
  'OBJECT__TEST_TYPE--362': (store) => store,
  'OBJECT__TEST_TYPE--363': (store) => store,
  'OBJECT__TEST_TYPE--364': (store) => store,
  'OBJECT__TEST_TYPE--365': (store) => store,
  'OBJECT__TEST_TYPE--366': (store) => store,
  'OBJECT__TEST_TYPE--367': (store) => store,
  'OBJECT__TEST_TYPE--368': (store) => store,
  'OBJECT__TEST_TYPE--369': (store) => store,
  'OBJECT__TEST_TYPE--370': (store) => store,
  'OBJECT__TEST_TYPE--371': (store) => store,
  'OBJECT__TEST_TYPE--372': (store) => store,
  'OBJECT__TEST_TYPE--373': (store) => store,
  'OBJECT__TEST_TYPE--374': (store) => store,
  'OBJECT__TEST_TYPE--375': (store) => store,
  'OBJECT__TEST_TYPE--376': (store) => store,
  'OBJECT__TEST_TYPE--377': (store) => store,
  'OBJECT__TEST_TYPE--378': (store) => store,
  'OBJECT__TEST_TYPE--379': (store) => store,
  'OBJECT__TEST_TYPE--380': (store) => store,
  'OBJECT__TEST_TYPE--381': (store) => store,
  'OBJECT__TEST_TYPE--382': (store) => store,
  'OBJECT__TEST_TYPE--383': (store) => store,
  'OBJECT__TEST_TYPE--384': (store) => store,
  'OBJECT__TEST_TYPE--385': (store) => store,
  'OBJECT__TEST_TYPE--386': (store) => store,
  'OBJECT__TEST_TYPE--387': (store) => store,
  'OBJECT__TEST_TYPE--388': (store) => store,
  'OBJECT__TEST_TYPE--389': (store) => store,
  'OBJECT__TEST_TYPE--390': (store) => store,
  'OBJECT__TEST_TYPE--391': (store) => store,
  'OBJECT__TEST_TYPE--392': (store) => store,
  'OBJECT__TEST_TYPE--393': (store) => store,
  'OBJECT__TEST_TYPE--394': (store) => store,
  'OBJECT__TEST_TYPE--395': (store) => store,
  'OBJECT__TEST_TYPE--396': (store) => store,
  'OBJECT__TEST_TYPE--397': (store) => store,
  'OBJECT__TEST_TYPE--398': (store) => store,
  'OBJECT__TEST_TYPE--399': (store) => store,
  'OBJECT__TEST_TYPE--400': (store) => store,
  'OBJECT__TEST_TYPE--401': (store) => store,
  'OBJECT__TEST_TYPE--402': (store) => store,
  'OBJECT__TEST_TYPE--403': (store) => store,
  'OBJECT__TEST_TYPE--404': (store) => store,
  'OBJECT__TEST_TYPE--405': (store) => store,
  'OBJECT__TEST_TYPE--406': (store) => store,
  'OBJECT__TEST_TYPE--407': (store) => store,
  'OBJECT__TEST_TYPE--408': (store) => store,
  'OBJECT__TEST_TYPE--409': (store) => store,
  'OBJECT__TEST_TYPE--410': (store) => store,
  'OBJECT__TEST_TYPE--411': (store) => store,
  'OBJECT__TEST_TYPE--412': (store) => store,
  'OBJECT__TEST_TYPE--413': (store) => store,
  'OBJECT__TEST_TYPE--414': (store) => store,
  'OBJECT__TEST_TYPE--415': (store) => store,
  'OBJECT__TEST_TYPE--416': (store) => store,
  'OBJECT__TEST_TYPE--417': (store) => store,
  'OBJECT__TEST_TYPE--418': (store) => store,
  'OBJECT__TEST_TYPE--419': (store) => store,
  'OBJECT__TEST_TYPE--420': (store) => store,
  'OBJECT__TEST_TYPE--421': (store) => store,
  'OBJECT__TEST_TYPE--422': (store) => store,
  'OBJECT__TEST_TYPE--423': (store) => store,
  'OBJECT__TEST_TYPE--424': (store) => store,
  'OBJECT__TEST_TYPE--425': (store) => store,
  'OBJECT__TEST_TYPE--426': (store) => store,
  'OBJECT__TEST_TYPE--427': (store) => store,
  'OBJECT__TEST_TYPE--428': (store) => store,
  'OBJECT__TEST_TYPE--429': (store) => store,
  'OBJECT__TEST_TYPE--430': (store) => store,
  'OBJECT__TEST_TYPE--431': (store) => store,
  'OBJECT__TEST_TYPE--432': (store) => store,
  'OBJECT__TEST_TYPE--433': (store) => store,
  'OBJECT__TEST_TYPE--434': (store) => store,
  'OBJECT__TEST_TYPE--435': (store) => store,
  'OBJECT__TEST_TYPE--436': (store) => store,
  'OBJECT__TEST_TYPE--437': (store) => store,
  'OBJECT__TEST_TYPE--438': (store) => store,
  'OBJECT__TEST_TYPE--439': (store) => store,
  'OBJECT__TEST_TYPE--440': (store) => store,
  'OBJECT__TEST_TYPE--441': (store) => store,
  'OBJECT__TEST_TYPE--442': (store) => store,
  'OBJECT__TEST_TYPE--443': (store) => store,
  'OBJECT__TEST_TYPE--444': (store) => store,
  'OBJECT__TEST_TYPE--445': (store) => store,
  'OBJECT__TEST_TYPE--446': (store) => store,
  'OBJECT__TEST_TYPE--447': (store) => store,
  'OBJECT__TEST_TYPE--448': (store) => store,
  'OBJECT__TEST_TYPE--449': (store) => store,
  'OBJECT__TEST_TYPE--450': (store) => store,
  'OBJECT__TEST_TYPE--451': (store) => store,
  'OBJECT__TEST_TYPE--452': (store) => store,
  'OBJECT__TEST_TYPE--453': (store) => store,
  'OBJECT__TEST_TYPE--454': (store) => store,
  'OBJECT__TEST_TYPE--455': (store) => store,
  'OBJECT__TEST_TYPE--456': (store) => store,
  'OBJECT__TEST_TYPE--457': (store) => store,
  'OBJECT__TEST_TYPE--458': (store) => store,
  'OBJECT__TEST_TYPE--459': (store) => store,
  'OBJECT__TEST_TYPE--460': (store) => store,
  'OBJECT__TEST_TYPE--461': (store) => store,
  'OBJECT__TEST_TYPE--462': (store) => store,
  'OBJECT__TEST_TYPE--463': (store) => store,
  'OBJECT__TEST_TYPE--464': (store) => store,
  'OBJECT__TEST_TYPE--465': (store) => store,
  'OBJECT__TEST_TYPE--466': (store) => store,
  'OBJECT__TEST_TYPE--467': (store) => store,
  'OBJECT__TEST_TYPE--468': (store) => store,
  'OBJECT__TEST_TYPE--469': (store) => store,
  'OBJECT__TEST_TYPE--470': (store) => store,
  'OBJECT__TEST_TYPE--471': (store) => store,
  'OBJECT__TEST_TYPE--472': (store) => store,
  'OBJECT__TEST_TYPE--473': (store) => store,
  'OBJECT__TEST_TYPE--474': (store) => store,
  'OBJECT__TEST_TYPE--475': (store) => store,
  'OBJECT__TEST_TYPE--476': (store) => store,
  'OBJECT__TEST_TYPE--477': (store) => store,
  'OBJECT__TEST_TYPE--478': (store) => store,
  'OBJECT__TEST_TYPE--479': (store) => store,
  'OBJECT__TEST_TYPE--480': (store) => store,
  'OBJECT__TEST_TYPE--481': (store) => store,
  'OBJECT__TEST_TYPE--482': (store) => store,
  'OBJECT__TEST_TYPE--483': (store) => store,
  'OBJECT__TEST_TYPE--484': (store) => store,
  'OBJECT__TEST_TYPE--485': (store) => store,
  'OBJECT__TEST_TYPE--486': (store) => store,
  'OBJECT__TEST_TYPE--487': (store) => store,
  'OBJECT__TEST_TYPE--488': (store) => store,
  'OBJECT__TEST_TYPE--489': (store) => store,
  'OBJECT__TEST_TYPE--490': (store) => store,
  'OBJECT__TEST_TYPE--491': (store) => store,
  'OBJECT__TEST_TYPE--492': (store) => store,
  'OBJECT__TEST_TYPE--493': (store) => store,
  'OBJECT__TEST_TYPE--494': (store) => store,
  'OBJECT__TEST_TYPE--495': (store) => store,
  'OBJECT__TEST_TYPE--496': (store) => store,
  'OBJECT__TEST_TYPE--497': (store) => store,
  'OBJECT__TEST_TYPE--498': (store) => store,
  'OBJECT__TEST_TYPE--499': (store) => store,
  [MIDDLE]: (store) => ({ ...store }),
  'OBJECT__TEST_TYPE--501': (store) => store,
  'OBJECT__TEST_TYPE--502': (store) => store,
  'OBJECT__TEST_TYPE--503': (store) => store,
  'OBJECT__TEST_TYPE--504': (store) => store,
  'OBJECT__TEST_TYPE--505': (store) => store,
  'OBJECT__TEST_TYPE--506': (store) => store,
  'OBJECT__TEST_TYPE--507': (store) => store,
  'OBJECT__TEST_TYPE--508': (store) => store,
  'OBJECT__TEST_TYPE--509': (store) => store,
  'OBJECT__TEST_TYPE--510': (store) => store,
  'OBJECT__TEST_TYPE--511': (store) => store,
  'OBJECT__TEST_TYPE--512': (store) => store,
  'OBJECT__TEST_TYPE--513': (store) => store,
  'OBJECT__TEST_TYPE--514': (store) => store,
  'OBJECT__TEST_TYPE--515': (store) => store,
  'OBJECT__TEST_TYPE--516': (store) => store,
  'OBJECT__TEST_TYPE--517': (store) => store,
  'OBJECT__TEST_TYPE--518': (store) => store,
  'OBJECT__TEST_TYPE--519': (store) => store,
  'OBJECT__TEST_TYPE--520': (store) => store,
  'OBJECT__TEST_TYPE--521': (store) => store,
  'OBJECT__TEST_TYPE--522': (store) => store,
  'OBJECT__TEST_TYPE--523': (store) => store,
  'OBJECT__TEST_TYPE--524': (store) => store,
  'OBJECT__TEST_TYPE--525': (store) => store,
  'OBJECT__TEST_TYPE--526': (store) => store,
  'OBJECT__TEST_TYPE--527': (store) => store,
  'OBJECT__TEST_TYPE--528': (store) => store,
  'OBJECT__TEST_TYPE--529': (store) => store,
  'OBJECT__TEST_TYPE--530': (store) => store,
  'OBJECT__TEST_TYPE--531': (store) => store,
  'OBJECT__TEST_TYPE--532': (store) => store,
  'OBJECT__TEST_TYPE--533': (store) => store,
  'OBJECT__TEST_TYPE--534': (store) => store,
  'OBJECT__TEST_TYPE--535': (store) => store,
  'OBJECT__TEST_TYPE--536': (store) => store,
  'OBJECT__TEST_TYPE--537': (store) => store,
  'OBJECT__TEST_TYPE--538': (store) => store,
  'OBJECT__TEST_TYPE--539': (store) => store,
  'OBJECT__TEST_TYPE--540': (store) => store,
  'OBJECT__TEST_TYPE--541': (store) => store,
  'OBJECT__TEST_TYPE--542': (store) => store,
  'OBJECT__TEST_TYPE--543': (store) => store,
  'OBJECT__TEST_TYPE--544': (store) => store,
  'OBJECT__TEST_TYPE--545': (store) => store,
  'OBJECT__TEST_TYPE--546': (store) => store,
  'OBJECT__TEST_TYPE--547': (store) => store,
  'OBJECT__TEST_TYPE--548': (store) => store,
  'OBJECT__TEST_TYPE--549': (store) => store,
  'OBJECT__TEST_TYPE--550': (store) => store,
  'OBJECT__TEST_TYPE--551': (store) => store,
  'OBJECT__TEST_TYPE--552': (store) => store,
  'OBJECT__TEST_TYPE--553': (store) => store,
  'OBJECT__TEST_TYPE--554': (store) => store,
  'OBJECT__TEST_TYPE--555': (store) => store,
  'OBJECT__TEST_TYPE--556': (store) => store,
  'OBJECT__TEST_TYPE--557': (store) => store,
  'OBJECT__TEST_TYPE--558': (store) => store,
  'OBJECT__TEST_TYPE--559': (store) => store,
  'OBJECT__TEST_TYPE--560': (store) => store,
  'OBJECT__TEST_TYPE--561': (store) => store,
  'OBJECT__TEST_TYPE--562': (store) => store,
  'OBJECT__TEST_TYPE--563': (store) => store,
  'OBJECT__TEST_TYPE--564': (store) => store,
  'OBJECT__TEST_TYPE--565': (store) => store,
  'OBJECT__TEST_TYPE--566': (store) => store,
  'OBJECT__TEST_TYPE--567': (store) => store,
  'OBJECT__TEST_TYPE--568': (store) => store,
  'OBJECT__TEST_TYPE--569': (store) => store,
  'OBJECT__TEST_TYPE--570': (store) => store,
  'OBJECT__TEST_TYPE--571': (store) => store,
  'OBJECT__TEST_TYPE--572': (store) => store,
  'OBJECT__TEST_TYPE--573': (store) => store,
  'OBJECT__TEST_TYPE--574': (store) => store,
  'OBJECT__TEST_TYPE--575': (store) => store,
  'OBJECT__TEST_TYPE--576': (store) => store,
  'OBJECT__TEST_TYPE--577': (store) => store,
  'OBJECT__TEST_TYPE--578': (store) => store,
  'OBJECT__TEST_TYPE--579': (store) => store,
  'OBJECT__TEST_TYPE--580': (store) => store,
  'OBJECT__TEST_TYPE--581': (store) => store,
  'OBJECT__TEST_TYPE--582': (store) => store,
  'OBJECT__TEST_TYPE--583': (store) => store,
  'OBJECT__TEST_TYPE--584': (store) => store,
  'OBJECT__TEST_TYPE--585': (store) => store,
  'OBJECT__TEST_TYPE--586': (store) => store,
  'OBJECT__TEST_TYPE--587': (store) => store,
  'OBJECT__TEST_TYPE--588': (store) => store,
  'OBJECT__TEST_TYPE--589': (store) => store,
  'OBJECT__TEST_TYPE--590': (store) => store,
  'OBJECT__TEST_TYPE--591': (store) => store,
  'OBJECT__TEST_TYPE--592': (store) => store,
  'OBJECT__TEST_TYPE--593': (store) => store,
  'OBJECT__TEST_TYPE--594': (store) => store,
  'OBJECT__TEST_TYPE--595': (store) => store,
  'OBJECT__TEST_TYPE--596': (store) => store,
  'OBJECT__TEST_TYPE--597': (store) => store,
  'OBJECT__TEST_TYPE--598': (store) => store,
  'OBJECT__TEST_TYPE--599': (store) => store,
  'OBJECT__TEST_TYPE--600': (store) => store,
  'OBJECT__TEST_TYPE--601': (store) => store,
  'OBJECT__TEST_TYPE--602': (store) => store,
  'OBJECT__TEST_TYPE--603': (store) => store,
  'OBJECT__TEST_TYPE--604': (store) => store,
  'OBJECT__TEST_TYPE--605': (store) => store,
  'OBJECT__TEST_TYPE--606': (store) => store,
  'OBJECT__TEST_TYPE--607': (store) => store,
  'OBJECT__TEST_TYPE--608': (store) => store,
  'OBJECT__TEST_TYPE--609': (store) => store,
  'OBJECT__TEST_TYPE--610': (store) => store,
  'OBJECT__TEST_TYPE--611': (store) => store,
  'OBJECT__TEST_TYPE--612': (store) => store,
  'OBJECT__TEST_TYPE--613': (store) => store,
  'OBJECT__TEST_TYPE--614': (store) => store,
  'OBJECT__TEST_TYPE--615': (store) => store,
  'OBJECT__TEST_TYPE--616': (store) => store,
  'OBJECT__TEST_TYPE--617': (store) => store,
  'OBJECT__TEST_TYPE--618': (store) => store,
  'OBJECT__TEST_TYPE--619': (store) => store,
  'OBJECT__TEST_TYPE--620': (store) => store,
  'OBJECT__TEST_TYPE--621': (store) => store,
  'OBJECT__TEST_TYPE--622': (store) => store,
  'OBJECT__TEST_TYPE--623': (store) => store,
  'OBJECT__TEST_TYPE--624': (store) => store,
  'OBJECT__TEST_TYPE--625': (store) => store,
  'OBJECT__TEST_TYPE--626': (store) => store,
  'OBJECT__TEST_TYPE--627': (store) => store,
  'OBJECT__TEST_TYPE--628': (store) => store,
  'OBJECT__TEST_TYPE--629': (store) => store,
  'OBJECT__TEST_TYPE--630': (store) => store,
  'OBJECT__TEST_TYPE--631': (store) => store,
  'OBJECT__TEST_TYPE--632': (store) => store,
  'OBJECT__TEST_TYPE--633': (store) => store,
  'OBJECT__TEST_TYPE--634': (store) => store,
  'OBJECT__TEST_TYPE--635': (store) => store,
  'OBJECT__TEST_TYPE--636': (store) => store,
  'OBJECT__TEST_TYPE--637': (store) => store,
  'OBJECT__TEST_TYPE--638': (store) => store,
  'OBJECT__TEST_TYPE--639': (store) => store,
  'OBJECT__TEST_TYPE--640': (store) => store,
  'OBJECT__TEST_TYPE--641': (store) => store,
  'OBJECT__TEST_TYPE--642': (store) => store,
  'OBJECT__TEST_TYPE--643': (store) => store,
  'OBJECT__TEST_TYPE--644': (store) => store,
  'OBJECT__TEST_TYPE--645': (store) => store,
  'OBJECT__TEST_TYPE--646': (store) => store,
  'OBJECT__TEST_TYPE--647': (store) => store,
  'OBJECT__TEST_TYPE--648': (store) => store,
  'OBJECT__TEST_TYPE--649': (store) => store,
  'OBJECT__TEST_TYPE--650': (store) => store,
  'OBJECT__TEST_TYPE--651': (store) => store,
  'OBJECT__TEST_TYPE--652': (store) => store,
  'OBJECT__TEST_TYPE--653': (store) => store,
  'OBJECT__TEST_TYPE--654': (store) => store,
  'OBJECT__TEST_TYPE--655': (store) => store,
  'OBJECT__TEST_TYPE--656': (store) => store,
  'OBJECT__TEST_TYPE--657': (store) => store,
  'OBJECT__TEST_TYPE--658': (store) => store,
  'OBJECT__TEST_TYPE--659': (store) => store,
  'OBJECT__TEST_TYPE--660': (store) => store,
  'OBJECT__TEST_TYPE--661': (store) => store,
  'OBJECT__TEST_TYPE--662': (store) => store,
  'OBJECT__TEST_TYPE--663': (store) => store,
  'OBJECT__TEST_TYPE--664': (store) => store,
  'OBJECT__TEST_TYPE--665': (store) => store,
  'OBJECT__TEST_TYPE--666': (store) => store,
  'OBJECT__TEST_TYPE--667': (store) => store,
  'OBJECT__TEST_TYPE--668': (store) => store,
  'OBJECT__TEST_TYPE--669': (store) => store,
  'OBJECT__TEST_TYPE--670': (store) => store,
  'OBJECT__TEST_TYPE--671': (store) => store,
  'OBJECT__TEST_TYPE--672': (store) => store,
  'OBJECT__TEST_TYPE--673': (store) => store,
  'OBJECT__TEST_TYPE--674': (store) => store,
  'OBJECT__TEST_TYPE--675': (store) => store,
  'OBJECT__TEST_TYPE--676': (store) => store,
  'OBJECT__TEST_TYPE--677': (store) => store,
  'OBJECT__TEST_TYPE--678': (store) => store,
  'OBJECT__TEST_TYPE--679': (store) => store,
  'OBJECT__TEST_TYPE--680': (store) => store,
  'OBJECT__TEST_TYPE--681': (store) => store,
  'OBJECT__TEST_TYPE--682': (store) => store,
  'OBJECT__TEST_TYPE--683': (store) => store,
  'OBJECT__TEST_TYPE--684': (store) => store,
  'OBJECT__TEST_TYPE--685': (store) => store,
  'OBJECT__TEST_TYPE--686': (store) => store,
  'OBJECT__TEST_TYPE--687': (store) => store,
  'OBJECT__TEST_TYPE--688': (store) => store,
  'OBJECT__TEST_TYPE--689': (store) => store,
  'OBJECT__TEST_TYPE--690': (store) => store,
  'OBJECT__TEST_TYPE--691': (store) => store,
  'OBJECT__TEST_TYPE--692': (store) => store,
  'OBJECT__TEST_TYPE--693': (store) => store,
  'OBJECT__TEST_TYPE--694': (store) => store,
  'OBJECT__TEST_TYPE--695': (store) => store,
  'OBJECT__TEST_TYPE--696': (store) => store,
  'OBJECT__TEST_TYPE--697': (store) => store,
  'OBJECT__TEST_TYPE--698': (store) => store,
  'OBJECT__TEST_TYPE--699': (store) => store,
  'OBJECT__TEST_TYPE--700': (store) => store,
  'OBJECT__TEST_TYPE--701': (store) => store,
  'OBJECT__TEST_TYPE--702': (store) => store,
  'OBJECT__TEST_TYPE--703': (store) => store,
  'OBJECT__TEST_TYPE--704': (store) => store,
  'OBJECT__TEST_TYPE--705': (store) => store,
  'OBJECT__TEST_TYPE--706': (store) => store,
  'OBJECT__TEST_TYPE--707': (store) => store,
  'OBJECT__TEST_TYPE--708': (store) => store,
  'OBJECT__TEST_TYPE--709': (store) => store,
  'OBJECT__TEST_TYPE--710': (store) => store,
  'OBJECT__TEST_TYPE--711': (store) => store,
  'OBJECT__TEST_TYPE--712': (store) => store,
  'OBJECT__TEST_TYPE--713': (store) => store,
  'OBJECT__TEST_TYPE--714': (store) => store,
  'OBJECT__TEST_TYPE--715': (store) => store,
  'OBJECT__TEST_TYPE--716': (store) => store,
  'OBJECT__TEST_TYPE--717': (store) => store,
  'OBJECT__TEST_TYPE--718': (store) => store,
  'OBJECT__TEST_TYPE--719': (store) => store,
  'OBJECT__TEST_TYPE--720': (store) => store,
  'OBJECT__TEST_TYPE--721': (store) => store,
  'OBJECT__TEST_TYPE--722': (store) => store,
  'OBJECT__TEST_TYPE--723': (store) => store,
  'OBJECT__TEST_TYPE--724': (store) => store,
  'OBJECT__TEST_TYPE--725': (store) => store,
  'OBJECT__TEST_TYPE--726': (store) => store,
  'OBJECT__TEST_TYPE--727': (store) => store,
  'OBJECT__TEST_TYPE--728': (store) => store,
  'OBJECT__TEST_TYPE--729': (store) => store,
  'OBJECT__TEST_TYPE--730': (store) => store,
  'OBJECT__TEST_TYPE--731': (store) => store,
  'OBJECT__TEST_TYPE--732': (store) => store,
  'OBJECT__TEST_TYPE--733': (store) => store,
  'OBJECT__TEST_TYPE--734': (store) => store,
  'OBJECT__TEST_TYPE--735': (store) => store,
  'OBJECT__TEST_TYPE--736': (store) => store,
  'OBJECT__TEST_TYPE--737': (store) => store,
  'OBJECT__TEST_TYPE--738': (store) => store,
  'OBJECT__TEST_TYPE--739': (store) => store,
  'OBJECT__TEST_TYPE--740': (store) => store,
  'OBJECT__TEST_TYPE--741': (store) => store,
  'OBJECT__TEST_TYPE--742': (store) => store,
  'OBJECT__TEST_TYPE--743': (store) => store,
  'OBJECT__TEST_TYPE--744': (store) => store,
  'OBJECT__TEST_TYPE--745': (store) => store,
  'OBJECT__TEST_TYPE--746': (store) => store,
  'OBJECT__TEST_TYPE--747': (store) => store,
  'OBJECT__TEST_TYPE--748': (store) => store,
  'OBJECT__TEST_TYPE--749': (store) => store,
  'OBJECT__TEST_TYPE--750': (store) => store,
  'OBJECT__TEST_TYPE--751': (store) => store,
  'OBJECT__TEST_TYPE--752': (store) => store,
  'OBJECT__TEST_TYPE--753': (store) => store,
  'OBJECT__TEST_TYPE--754': (store) => store,
  'OBJECT__TEST_TYPE--755': (store) => store,
  'OBJECT__TEST_TYPE--756': (store) => store,
  'OBJECT__TEST_TYPE--757': (store) => store,
  'OBJECT__TEST_TYPE--758': (store) => store,
  'OBJECT__TEST_TYPE--759': (store) => store,
  'OBJECT__TEST_TYPE--760': (store) => store,
  'OBJECT__TEST_TYPE--761': (store) => store,
  'OBJECT__TEST_TYPE--762': (store) => store,
  'OBJECT__TEST_TYPE--763': (store) => store,
  'OBJECT__TEST_TYPE--764': (store) => store,
  'OBJECT__TEST_TYPE--765': (store) => store,
  'OBJECT__TEST_TYPE--766': (store) => store,
  'OBJECT__TEST_TYPE--767': (store) => store,
  'OBJECT__TEST_TYPE--768': (store) => store,
  'OBJECT__TEST_TYPE--769': (store) => store,
  'OBJECT__TEST_TYPE--770': (store) => store,
  'OBJECT__TEST_TYPE--771': (store) => store,
  'OBJECT__TEST_TYPE--772': (store) => store,
  'OBJECT__TEST_TYPE--773': (store) => store,
  'OBJECT__TEST_TYPE--774': (store) => store,
  'OBJECT__TEST_TYPE--775': (store) => store,
  'OBJECT__TEST_TYPE--776': (store) => store,
  'OBJECT__TEST_TYPE--777': (store) => store,
  'OBJECT__TEST_TYPE--778': (store) => store,
  'OBJECT__TEST_TYPE--779': (store) => store,
  'OBJECT__TEST_TYPE--780': (store) => store,
  'OBJECT__TEST_TYPE--781': (store) => store,
  'OBJECT__TEST_TYPE--782': (store) => store,
  'OBJECT__TEST_TYPE--783': (store) => store,
  'OBJECT__TEST_TYPE--784': (store) => store,
  'OBJECT__TEST_TYPE--785': (store) => store,
  'OBJECT__TEST_TYPE--786': (store) => store,
  'OBJECT__TEST_TYPE--787': (store) => store,
  'OBJECT__TEST_TYPE--788': (store) => store,
  'OBJECT__TEST_TYPE--789': (store) => store,
  'OBJECT__TEST_TYPE--790': (store) => store,
  'OBJECT__TEST_TYPE--791': (store) => store,
  'OBJECT__TEST_TYPE--792': (store) => store,
  'OBJECT__TEST_TYPE--793': (store) => store,
  'OBJECT__TEST_TYPE--794': (store) => store,
  'OBJECT__TEST_TYPE--795': (store) => store,
  'OBJECT__TEST_TYPE--796': (store) => store,
  'OBJECT__TEST_TYPE--797': (store) => store,
  'OBJECT__TEST_TYPE--798': (store) => store,
  'OBJECT__TEST_TYPE--799': (store) => store,
  'OBJECT__TEST_TYPE--800': (store) => store,
  'OBJECT__TEST_TYPE--801': (store) => store,
  'OBJECT__TEST_TYPE--802': (store) => store,
  'OBJECT__TEST_TYPE--803': (store) => store,
  'OBJECT__TEST_TYPE--804': (store) => store,
  'OBJECT__TEST_TYPE--805': (store) => store,
  'OBJECT__TEST_TYPE--806': (store) => store,
  'OBJECT__TEST_TYPE--807': (store) => store,
  'OBJECT__TEST_TYPE--808': (store) => store,
  'OBJECT__TEST_TYPE--809': (store) => store,
  'OBJECT__TEST_TYPE--810': (store) => store,
  'OBJECT__TEST_TYPE--811': (store) => store,
  'OBJECT__TEST_TYPE--812': (store) => store,
  'OBJECT__TEST_TYPE--813': (store) => store,
  'OBJECT__TEST_TYPE--814': (store) => store,
  'OBJECT__TEST_TYPE--815': (store) => store,
  'OBJECT__TEST_TYPE--816': (store) => store,
  'OBJECT__TEST_TYPE--817': (store) => store,
  'OBJECT__TEST_TYPE--818': (store) => store,
  'OBJECT__TEST_TYPE--819': (store) => store,
  'OBJECT__TEST_TYPE--820': (store) => store,
  'OBJECT__TEST_TYPE--821': (store) => store,
  'OBJECT__TEST_TYPE--822': (store) => store,
  'OBJECT__TEST_TYPE--823': (store) => store,
  'OBJECT__TEST_TYPE--824': (store) => store,
  'OBJECT__TEST_TYPE--825': (store) => store,
  'OBJECT__TEST_TYPE--826': (store) => store,
  'OBJECT__TEST_TYPE--827': (store) => store,
  'OBJECT__TEST_TYPE--828': (store) => store,
  'OBJECT__TEST_TYPE--829': (store) => store,
  'OBJECT__TEST_TYPE--830': (store) => store,
  'OBJECT__TEST_TYPE--831': (store) => store,
  'OBJECT__TEST_TYPE--832': (store) => store,
  'OBJECT__TEST_TYPE--833': (store) => store,
  'OBJECT__TEST_TYPE--834': (store) => store,
  'OBJECT__TEST_TYPE--835': (store) => store,
  'OBJECT__TEST_TYPE--836': (store) => store,
  'OBJECT__TEST_TYPE--837': (store) => store,
  'OBJECT__TEST_TYPE--838': (store) => store,
  'OBJECT__TEST_TYPE--839': (store) => store,
  'OBJECT__TEST_TYPE--840': (store) => store,
  'OBJECT__TEST_TYPE--841': (store) => store,
  'OBJECT__TEST_TYPE--842': (store) => store,
  'OBJECT__TEST_TYPE--843': (store) => store,
  'OBJECT__TEST_TYPE--844': (store) => store,
  'OBJECT__TEST_TYPE--845': (store) => store,
  'OBJECT__TEST_TYPE--846': (store) => store,
  'OBJECT__TEST_TYPE--847': (store) => store,
  'OBJECT__TEST_TYPE--848': (store) => store,
  'OBJECT__TEST_TYPE--849': (store) => store,
  'OBJECT__TEST_TYPE--850': (store) => store,
  'OBJECT__TEST_TYPE--851': (store) => store,
  'OBJECT__TEST_TYPE--852': (store) => store,
  'OBJECT__TEST_TYPE--853': (store) => store,
  'OBJECT__TEST_TYPE--854': (store) => store,
  'OBJECT__TEST_TYPE--855': (store) => store,
  'OBJECT__TEST_TYPE--856': (store) => store,
  'OBJECT__TEST_TYPE--857': (store) => store,
  'OBJECT__TEST_TYPE--858': (store) => store,
  'OBJECT__TEST_TYPE--859': (store) => store,
  'OBJECT__TEST_TYPE--860': (store) => store,
  'OBJECT__TEST_TYPE--861': (store) => store,
  'OBJECT__TEST_TYPE--862': (store) => store,
  'OBJECT__TEST_TYPE--863': (store) => store,
  'OBJECT__TEST_TYPE--864': (store) => store,
  'OBJECT__TEST_TYPE--865': (store) => store,
  'OBJECT__TEST_TYPE--866': (store) => store,
  'OBJECT__TEST_TYPE--867': (store) => store,
  'OBJECT__TEST_TYPE--868': (store) => store,
  'OBJECT__TEST_TYPE--869': (store) => store,
  'OBJECT__TEST_TYPE--870': (store) => store,
  'OBJECT__TEST_TYPE--871': (store) => store,
  'OBJECT__TEST_TYPE--872': (store) => store,
  'OBJECT__TEST_TYPE--873': (store) => store,
  'OBJECT__TEST_TYPE--874': (store) => store,
  'OBJECT__TEST_TYPE--875': (store) => store,
  'OBJECT__TEST_TYPE--876': (store) => store,
  'OBJECT__TEST_TYPE--877': (store) => store,
  'OBJECT__TEST_TYPE--878': (store) => store,
  'OBJECT__TEST_TYPE--879': (store) => store,
  'OBJECT__TEST_TYPE--880': (store) => store,
  'OBJECT__TEST_TYPE--881': (store) => store,
  'OBJECT__TEST_TYPE--882': (store) => store,
  'OBJECT__TEST_TYPE--883': (store) => store,
  'OBJECT__TEST_TYPE--884': (store) => store,
  'OBJECT__TEST_TYPE--885': (store) => store,
  'OBJECT__TEST_TYPE--886': (store) => store,
  'OBJECT__TEST_TYPE--887': (store) => store,
  'OBJECT__TEST_TYPE--888': (store) => store,
  'OBJECT__TEST_TYPE--889': (store) => store,
  'OBJECT__TEST_TYPE--890': (store) => store,
  'OBJECT__TEST_TYPE--891': (store) => store,
  'OBJECT__TEST_TYPE--892': (store) => store,
  'OBJECT__TEST_TYPE--893': (store) => store,
  'OBJECT__TEST_TYPE--894': (store) => store,
  'OBJECT__TEST_TYPE--895': (store) => store,
  'OBJECT__TEST_TYPE--896': (store) => store,
  'OBJECT__TEST_TYPE--897': (store) => store,
  'OBJECT__TEST_TYPE--898': (store) => store,
  'OBJECT__TEST_TYPE--899': (store) => store,
  'OBJECT__TEST_TYPE--900': (store) => store,
  'OBJECT__TEST_TYPE--901': (store) => store,
  'OBJECT__TEST_TYPE--902': (store) => store,
  'OBJECT__TEST_TYPE--903': (store) => store,
  'OBJECT__TEST_TYPE--904': (store) => store,
  'OBJECT__TEST_TYPE--905': (store) => store,
  'OBJECT__TEST_TYPE--906': (store) => store,
  'OBJECT__TEST_TYPE--907': (store) => store,
  'OBJECT__TEST_TYPE--908': (store) => store,
  'OBJECT__TEST_TYPE--909': (store) => store,
  'OBJECT__TEST_TYPE--910': (store) => store,
  'OBJECT__TEST_TYPE--911': (store) => store,
  'OBJECT__TEST_TYPE--912': (store) => store,
  'OBJECT__TEST_TYPE--913': (store) => store,
  'OBJECT__TEST_TYPE--914': (store) => store,
  'OBJECT__TEST_TYPE--915': (store) => store,
  'OBJECT__TEST_TYPE--916': (store) => store,
  'OBJECT__TEST_TYPE--917': (store) => store,
  'OBJECT__TEST_TYPE--918': (store) => store,
  'OBJECT__TEST_TYPE--919': (store) => store,
  'OBJECT__TEST_TYPE--920': (store) => store,
  'OBJECT__TEST_TYPE--921': (store) => store,
  'OBJECT__TEST_TYPE--922': (store) => store,
  'OBJECT__TEST_TYPE--923': (store) => store,
  'OBJECT__TEST_TYPE--924': (store) => store,
  'OBJECT__TEST_TYPE--925': (store) => store,
  'OBJECT__TEST_TYPE--926': (store) => store,
  'OBJECT__TEST_TYPE--927': (store) => store,
  'OBJECT__TEST_TYPE--928': (store) => store,
  'OBJECT__TEST_TYPE--929': (store) => store,
  'OBJECT__TEST_TYPE--930': (store) => store,
  'OBJECT__TEST_TYPE--931': (store) => store,
  'OBJECT__TEST_TYPE--932': (store) => store,
  'OBJECT__TEST_TYPE--933': (store) => store,
  'OBJECT__TEST_TYPE--934': (store) => store,
  'OBJECT__TEST_TYPE--935': (store) => store,
  'OBJECT__TEST_TYPE--936': (store) => store,
  'OBJECT__TEST_TYPE--937': (store) => store,
  'OBJECT__TEST_TYPE--938': (store) => store,
  'OBJECT__TEST_TYPE--939': (store) => store,
  'OBJECT__TEST_TYPE--940': (store) => store,
  'OBJECT__TEST_TYPE--941': (store) => store,
  'OBJECT__TEST_TYPE--942': (store) => store,
  'OBJECT__TEST_TYPE--943': (store) => store,
  'OBJECT__TEST_TYPE--944': (store) => store,
  'OBJECT__TEST_TYPE--945': (store) => store,
  'OBJECT__TEST_TYPE--946': (store) => store,
  'OBJECT__TEST_TYPE--947': (store) => store,
  'OBJECT__TEST_TYPE--948': (store) => store,
  'OBJECT__TEST_TYPE--949': (store) => store,
  'OBJECT__TEST_TYPE--950': (store) => store,
  'OBJECT__TEST_TYPE--951': (store) => store,
  'OBJECT__TEST_TYPE--952': (store) => store,
  'OBJECT__TEST_TYPE--953': (store) => store,
  'OBJECT__TEST_TYPE--954': (store) => store,
  'OBJECT__TEST_TYPE--955': (store) => store,
  'OBJECT__TEST_TYPE--956': (store) => store,
  'OBJECT__TEST_TYPE--957': (store) => store,
  'OBJECT__TEST_TYPE--958': (store) => store,
  'OBJECT__TEST_TYPE--959': (store) => store,
  'OBJECT__TEST_TYPE--960': (store) => store,
  'OBJECT__TEST_TYPE--961': (store) => store,
  'OBJECT__TEST_TYPE--962': (store) => store,
  'OBJECT__TEST_TYPE--963': (store) => store,
  'OBJECT__TEST_TYPE--964': (store) => store,
  'OBJECT__TEST_TYPE--965': (store) => store,
  'OBJECT__TEST_TYPE--966': (store) => store,
  'OBJECT__TEST_TYPE--967': (store) => store,
  'OBJECT__TEST_TYPE--968': (store) => store,
  'OBJECT__TEST_TYPE--969': (store) => store,
  'OBJECT__TEST_TYPE--970': (store) => store,
  'OBJECT__TEST_TYPE--971': (store) => store,
  'OBJECT__TEST_TYPE--972': (store) => store,
  'OBJECT__TEST_TYPE--973': (store) => store,
  'OBJECT__TEST_TYPE--974': (store) => store,
  'OBJECT__TEST_TYPE--975': (store) => store,
  'OBJECT__TEST_TYPE--976': (store) => store,
  'OBJECT__TEST_TYPE--977': (store) => store,
  'OBJECT__TEST_TYPE--978': (store) => store,
  'OBJECT__TEST_TYPE--979': (store) => store,
  'OBJECT__TEST_TYPE--980': (store) => store,
  'OBJECT__TEST_TYPE--981': (store) => store,
  'OBJECT__TEST_TYPE--982': (store) => store,
  'OBJECT__TEST_TYPE--983': (store) => store,
  'OBJECT__TEST_TYPE--984': (store) => store,
  'OBJECT__TEST_TYPE--985': (store) => store,
  'OBJECT__TEST_TYPE--986': (store) => store,
  'OBJECT__TEST_TYPE--987': (store) => store,
  'OBJECT__TEST_TYPE--988': (store) => store,
  'OBJECT__TEST_TYPE--989': (store) => store,
  'OBJECT__TEST_TYPE--990': (store) => store,
  'OBJECT__TEST_TYPE--991': (store) => store,
  'OBJECT__TEST_TYPE--992': (store) => store,
  'OBJECT__TEST_TYPE--993': (store) => store,
  'OBJECT__TEST_TYPE--994': (store) => store,
  'OBJECT__TEST_TYPE--995': (store) => store,
  'OBJECT__TEST_TYPE--996': (store) => store,
  'OBJECT__TEST_TYPE--997': (store) => store,
  'OBJECT__TEST_TYPE--998': (store) => store,
  'OBJECT__TEST_TYPE--999': (store) => store,
  [LAST]: (store) => ({ ...store })
};

export default (store = initialStore, { type, cb = () => null }) => {
  if (!functions[type]) { return store; }

  const newStore = functions[type](store);

  cb();

  return newStore
}
